server.port=8081
spring.cloud.stream.bindings.input.group=Service-A
spring.cloud.stream.bindings.input.destination=input
spring.rabbitmq.host=192.168.2.238
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
